### ISSUE TITLE
Create Blocks

### ISSUE THREAD

**Issue by maximilian-zollbrecht** [Arne2/GameDesign#11]
After #7

**Comment by tgater** [comment]
6 new blocks added: leaves, sand, stone, cobble, spikes, and cactus

**Comment by Arne2** [comment]
We need:
- cactus
- steal beam
- wood
- concrete
- glass
- sandstone
- asphalt
- quicksand
- alternative spikes

**Comment by Arne2** [comment]
all needed blocks were created in #39
