### ISSUE TITLE
Story/Level-Themes

### ISSUE THREAD

**Issue by maximilian-zollbrecht** [Arne2/GameDesign#7]
Story of the spiders journey back home. With the accompanying level themes.

Creating the actual levels is not part of this issue.

**Comment by Arne2** [comment]
I though of:
After the spider woke up in the planes the spider notices a familiar smell from the woods.
Once the spider found the source of the smell - a mole - it tells you that he has seen the forrest and sends it through a cave. Unfortunatly this was the wrong way so at the time the spider found the way out of the cave it finds itself in a desert. Still believing it is following the right direction the spider proceeds until it finds a friendly fellow who acutally knows the way. This creature tells the spider that the forrest it is seeking is right behind a big city. After the spider overcame the dangers of the city it can finally enter its home forest. But it is not over yet. The forrest bears even more powerfull threats to the spider. If the spider is still able to survive it can get back to its family.

**Comment by Arne2** [comment]
city theme removed
